### ISSUE TITLE
Failed to compile (Windows 10)

### ISSUE THREAD

**Issue by cstrat** [wmira/react-playground-vscode#15]
## Failed to compile (Windows 10)

Tried removing the extension and re-installing to no avail. Anyone else experience this issue?

```
Failed to compile.

(webpack)/buildin/module.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* C:\Users\cstrat\.vscode\extensions\wmira.react-playground-vscode-0.0.11\node_modules\webpack\buildin\module.js
    Used by 1 module(s), i. e.
    C:\Users\cstrat\.vscode\extensions\wmira.react-playground-vscode-0.0.11\node_modules\punycode\punycode.js
* c:\Users\cstrat\.vscode\extensions\wmira.react-playground-vscode-0.0.11\node_modules\webpack\buildin\module.js
    Used by 4 module(s), i. e.
    c:\Users\cstrat\.vscode\extensions\wmira.react-playground-vscode-0.0.11\node_modules\json3\lib\json3.js
```

**Comment by kevin0311** [comment]
Yeah, I'm getting something similar, I guess (in Windows 10).  Looks like JSON5 is where a lot of the problems are coming from.

```
Failed to compile.

c:/Users/kevin0311/Documents/reactDev_2/sandbox/src/Menu.js
Module build failed: SyntaxError: c:\Users\kevin0311\Documents\reactDev_2\sandbox\.babelrc: Error while parsing JSON - Unexpected EOF at line 1 column 2 of the JSON5 data. Still to read: ""
	at error (c:\Users\kevin0311\.vscode\extensions\wmira.react-playground-vscode-0.0.11\node_modules\json5\lib\json5.js:56:25)
	at word (c:\Users\kevin0311\.vscode\extensions\wmira.react-playground-vscode-0.0.11\node_modules\json5\lib\json5.js:393:13)
	at value (c:\Users\kevin0311\.vscode\extensions\wmira.react-playground-vscode-0.0.11\node_modules\json5\lib\json5.js:493:56)
	at Object.parse (c:\Users\kevin0311\.vscode\extensions\wmira.react-playground-vscode-0.0.11\node_modules\json5\lib\json5.js:508:18)
	at ConfigChainBuilder.addConfig (c:\Users\kevin0311\.vscode\extensions\wmira.react-playground-vscode-0.0.11\node_modules\babel-core\lib\transformation\file\options\build-config-chain.js:150:65)
	at ConfigChainBuilder.findConfigs (c:\Users\kevin0311\.vscode\extensions\wmira.react-playground-vscode-0.0.11\node_modules\babel-core\lib\transformation\file\options\build-config-chain.js:96:16)
	at buildConfigChain (c:\Users\kevin0311\.vscode\extensions\wmira.react-playground-vscode-0.0.11\node_modules\babel-core\lib\transformation\file\options\build-config-chain.js:61:13)
	at OptionManager.init (c:\Users\kevin0311\.vscode\extensions\wmira.react-playground-vscode-0.0.11\node_modules\babel-core\lib\transformation\file\options\option-manager.js:354:58)
	at File.initOptions (c:\Users\kevin0311\.vscode\extensions\wmira.react-playground-vscode-0.0.11\node_modules\babel-core\lib\transformation\file\index.js:212:65)
	at new File (c:\Users\kevin0311\.vscode\extensions\wmira.react-playground-vscode-0.0.11\node_modules\babel-core\lib\transformation\file\index.js:135:24)
	at Pipeline.transform (c:\Users\kevin0311\.vscode\extensions\wmira.react-playground-vscode-0.0.11\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
	at transpile (c:\Users\kevin0311\.vscode\extensions\wmira.react-playground-vscode-0.0.11\node_modules\babel-loader\lib\index.js:46:20)
	at Object.module.exports (c:\Users\kevin0311\.vscode\extensions\wmira.react-playground-vscode-0.0.11\node_modules\babel-loader\lib\index.js:163:20)
 @ c:/Users/kevin0311/Documents/reactDev_2/.react-playground/index.js 15:12-82
 @ multi (webpack)-dev-server/client?http://localhost:9123 c:/Users/kevin0311/Documents/reactDev_2/.react-playground/index.js
```

**Comment by fadimtr** [comment]
any news how to fix this issue ?
